# Generated by Django 4.2.5 on 2024-01-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAApplicationRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='INBApplicationRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='control',
        ),
        migrations.AddField(
            model_name='collegestudentapplication',
            name='requirement',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='financialassistanceapplication',
            name='requirement',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='collegestudentassesment',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='a_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='b_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='c_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='d_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='e_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='base.collegestudentaccepted'),
        ),
        migrations.DeleteModel(
            name='CollegeRequirements',
        ),
        migrations.DeleteModel(
            name='FinancialAssistanceRequirement',
        ),
        migrations.DeleteModel(
            name='Student_Monitoring',
        ),
        migrations.AddField(
            model_name='inbapplicationrequirements',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collegestudentapplication'),
        ),
        migrations.AddField(
            model_name='inbapplicationrequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inbrequirementrepository'),
        ),
        migrations.AddField(
            model_name='faapplicationrequirements',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.financialassistanceapplication'),
        ),
        migrations.AddField(
            model_name='faapplicationrequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.farequirementrepository'),
        ),
    ]
