# Generated by Django 4.2.5 on 2023-12-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='a_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='b_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='c_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='d_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='e_sibling_DOB',
            field=models.DateField(default='00-00-0000'),
        ),
    ]
