# Generated by Django 4.2.5 on 2024-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_faapplicationrequirements_inbapplicationrequirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinforepositoryinb',
            name='school_year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
        migrations.AddField(
            model_name='collegestudentapplication',
            name='school_year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
    ]
