# Generated by Django 4.2.7 on 2024-01-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_financialassistanceapplication_a_sibling_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAApplicationRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='INBApplicationRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='control',
        ),
        migrations.AddField(
            model_name='collegestudentapplication',
            name='requirement',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='financialassistanceapplication',
            name='requirement',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='base.collegestudentaccepted'),
        ),
        migrations.DeleteModel(
            name='CollegeRequirements',
        ),
        migrations.DeleteModel(
            name='FinancialAssistanceRequirement',
        ),
        migrations.DeleteModel(
            name='Student_Monitoring',
        ),
        migrations.AddField(
            model_name='inbapplicationrequirements',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collegestudentapplication'),
        ),
        migrations.AddField(
            model_name='inbapplicationrequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inbrequirementrepository'),
        ),
        migrations.AddField(
            model_name='faapplicationrequirements',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.financialassistanceapplication'),
        ),
        migrations.AddField(
            model_name='faapplicationrequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.farequirementrepository'),
        ),
    ]
