# Generated by Django 4.2.7 on 2024-01-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_faapplicationrequirements_inbapplicationrequirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudentassesment',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
