# Generated by Django 4.2.6 on 2023-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_financialassistanceaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinforepositoryinb',
            name='school',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='collegestudentaccepted',
            name='school',
            field=models.CharField(default='', max_length=150),
        ),
    ]
