# Generated by Django 4.2.5 on 2023-11-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_inbcourse_school_inbcourse_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbcourse',
            name='school',
        ),
        migrations.AddField(
            model_name='inbcourse',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.inbschool'),
            preserve_default=False,
        ),
    ]
