# Generated by Django 4.2.5 on 2024-01-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_collegestudentaccepted_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='created_at',
        ),
        migrations.AddField(
            model_name='collegestudentapplication',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
