# Generated by Django 4.2.6 on 2023-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_applicantinforepositoryinb_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssistanceInfoRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
                ('fullname', models.CharField(default='', max_length=250)),
                ('date_of_birth', models.DateField(default='01-01-2001')),
                ('place_of_birth', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='Unknown', max_length=100)),
                ('email_address', models.EmailField(default='', max_length=100)),
                ('contact_no', models.CharField(default='', max_length=25)),
                ('general_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('school', models.CharField(default='', max_length=100)),
                ('school_address', models.CharField(default='', max_length=100)),
                ('track', models.CharField(default='', max_length=100)),
                ('strand', models.CharField(default='', max_length=100)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('father_age', models.SmallIntegerField(default='')),
                ('father_occupation', models.CharField(default='', max_length=100)),
                ('father_employer', models.CharField(default='', max_length=100)),
                ('father_income', models.IntegerField(default='')),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('mother_age', models.SmallIntegerField(default='')),
                ('mother_occupation', models.CharField(default='', max_length=100)),
                ('mother_employer', models.CharField(default='', max_length=100)),
                ('mother_income', models.IntegerField(default='')),
                ('sibling_count', models.SmallIntegerField(default='')),
                ('sibling_name', models.CharField(default='', max_length=100)),
                ('sibling_DOB', models.DateField(default='01-01-2001')),
                ('sibling_age', models.SmallIntegerField(default=0)),
                ('sibling_address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
