# Generated by Django 4.2.5 on 2024-01-06 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_collegestudentapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='year',
        ),
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='year',
        ),
        migrations.AddField(
            model_name='collegestudentaccepted',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collegestudentapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
