# Generated by Django 4.2.5 on 2024-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_collegestudentaccepted_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentaccepted',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
