# Generated by Django 4.2.7 on 2023-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_farequirementrepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_a',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_b',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_c',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_d',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_e',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_f',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_g',
        ),
        migrations.RemoveField(
            model_name='financialassistancerequirement',
            name='req_h',
        ),
    ]
