# Generated by Django 4.2.5 on 2024-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_collegestudentaccepted_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='INBScholars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('total_applicants', models.IntegerField(default=0)),
                ('total_accepted_applicants', models.IntegerField(default=0)),
                ('total_failed_applicants', models.IntegerField(default=0)),
                ('total_rejected_applicants', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='collegestudentaccepted',
            name='remarks',
            field=models.CharField(default='', max_length=500),
        ),
    ]
