# Generated by Django 4.2.5 on 2024-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_inbscholars_collegestudentaccepted_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('admitted_applicants', models.IntegerField(default=0)),
                ('applied_applicants', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='collegestudentaccepted',
            name='grant',
            field=models.CharField(default='100%', max_length=500),
        ),
    ]
