# Generated by Django 4.2.7 on 2024-01-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_inbscholars_collegestudentaccepted_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('admitted_applicants', models.IntegerField(default=0)),
                ('applied_applicants', models.IntegerField(default=0)),
            ],
        ),
    ]
