# Generated by Django 4.2.7 on 2023-12-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_address_applicantinforepositoryinb_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinforepositoryinb',
            old_name='barangay',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='collegestudentapplication',
            old_name='barangay',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='applicantinforepositoryinb',
            name='blkstr',
        ),
        migrations.RemoveField(
            model_name='applicantinforepositoryinb',
            name='city',
        ),
        migrations.RemoveField(
            model_name='applicantinforepositoryinb',
            name='province',
        ),
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='blkstr',
        ),
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='province',
        ),
    ]
