# Generated by Django 4.2.5 on 2023-11-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_inbschool_inbcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbcourse',
            old_name='name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='inbschool',
            old_name='name',
            new_name='school',
        ),
    ]
