# Generated by Django 4.2.5 on 2024-01-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_applicanttracker_collegestudentaccepted_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='created_at',
        ),
    ]
