# Generated by Django 4.2.7 on 2023-12-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_address_collegestudentapplication_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinforepositoryinb',
            old_name='address',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='financialassistanceapplication',
            old_name='address',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='financialassistanceinforepository',
            old_name='address',
            new_name='barangay',
        ),
        migrations.AddField(
            model_name='applicantinforepositoryinb',
            name='blkstr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantinforepositoryinb',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantinforepositoryinb',
            name='province',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceapplication',
            name='blkstr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceapplication',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceapplication',
            name='province',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceinforepository',
            name='blkstr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceinforepository',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceinforepository',
            name='province',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
