# Generated by Django 4.2.7 on 2023-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_address_applicantinforepositoryinb_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudentAssesment',
            fields=[
                ('control_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAssistanceAssesment',
            fields=[
                ('control_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('school_year', models.CharField(default='1st Years', max_length=50)),
                ('course', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
