# Generated by Django 4.2.5 on 2024-01-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_collegestudentapplication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudentapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
