# Generated by Django 4.2.7 on 2023-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_collegestudentassesment_financialassistanceassesment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinforepositoryinb',
            name='father_voter_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantinforepositoryinb',
            name='guardian_voter_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantinforepositoryinb',
            name='mother_voter_status',
            field=models.BooleanField(default=False),
        ),
    ]
