# Generated by Django 4.2.7 on 2024-01-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_collegestudentapplication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialassistanceaccepted',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='financialassistanceassesment',
            name='school_year',
        ),
    ]
