# Generated by Django 4.2.7 on 2023-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_collegestudentassesment_financialassistanceassesment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentassesment',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
