# Generated by Django 4.2.7 on 2024-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_financialassistanceaccepted_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialassistanceaccepted',
            name='status',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
        migrations.AddField(
            model_name='financialassistanceassesment',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
