# Generated by Django 4.2.5 on 2024-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_applicanttracker_inbapplicanttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinforepositoryinb',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
