# Generated by Django 4.2.7 on 2023-12-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_collegestudentassesment_status'),
        ('base', '0015_alter_applicantinforepositoryinb_father_voter_status_and_more'),
    ]

    operations = [
    ]
