# Generated by Django 4.2.5 on 2024-01-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_applicantinforepositoryinb_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='gwa',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='grade',
            field=models.IntegerField(default='0'),
        ),
    ]
