# Generated by Django 4.2.7 on 2024-01-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_financialassistanceaccepted_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialassistanceaccepted',
            name='status',
        ),
    ]
