# Generated by Django 4.2.5 on 2024-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_subject_studentgrade_gwa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='control_number',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
