# Generated by Django 4.2.7 on 2023-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20231211_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudentassesment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
