# Generated by Django 4.2.5 on 2023-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_collegestudentassesment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=1)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
    ]
