# Generated by Django 4.2.5 on 2024-01-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_studentgrade_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentaccepted',
            name='semester',
            field=models.CharField(default='1st Semester%', max_length=500),
        ),
    ]
