# Generated by Django 4.2.5 on 2023-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_subject_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_monitoring',
            name='gwa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
