# Generated by Django 4.2.5 on 2023-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_studentgrade_grade_alter_studentgrade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='grade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
