# Generated by Django 4.2.5 on 2024-01-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_userprofile_position_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
