# Generated by Django 4.2.5 on 2023-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='subject_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
