# Generated by Django 4.2.5 on 2023-12-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_studentgrade_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='subject_code',
        ),
    ]
