# Generated by Django 4.2.7 on 2024-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_financialassistanceaccepted_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentrejected',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegestudentrejected',
            name='school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
