# Generated by Django 4.2.5 on 2023-12-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_studentgrade_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='count',
        ),
    ]
