# Generated by Django 4.2.5 on 2024-01-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_collegestudentapplication_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='user',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
