# Generated by Django 4.2.7 on 2023-12-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentassesment',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
