# Generated by Django 4.2.5 on 2024-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_collegestudentapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
