# Generated by Django 4.2.7 on 2023-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_collegestudentassesment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudentassesment',
            name='school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
