# Generated by Django 4.2.5 on 2024-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_logentry_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='staff_name',
            new_name='staff_first_name',
        ),
        migrations.AddField(
            model_name='logentry',
            name='staff_last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
