# Generated by Django 4.2.7 on 2023-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_collegestudentassesment_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudentaccepted',
            name='school_year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
    ]
