# Generated by Django 4.2.5 on 2024-01-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_staff_name_logentry_staff_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='staff_first_name',
            new_name='staff_username',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='staff_last_name',
        ),
    ]
