# Generated by Django 4.2.5 on 2023-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_course_financialassistanceaccepted_strand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudentapplication',
            name='father_voter_status',
            field=models.CharField(default='Not Registered', max_length=100),
        ),
        migrations.AlterField(
            model_name='collegestudentapplication',
            name='guardian_voter_status',
            field=models.CharField(default='Not Registered', max_length=100),
        ),
        migrations.AlterField(
            model_name='collegestudentapplication',
            name='mother_voter_status',
            field=models.CharField(default='Not Registered', max_length=100),
        ),
    ]
