# Generated by Django 4.2.5 on 2023-11-30 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_inbcourse_school_inbcourse_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbcourse',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inbschool'),
        ),
    ]
