# Generated by Django 4.2.7 on 2023-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_inbcourse_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbcourse',
            name='school',
        ),
    ]
