# Generated by Django 4.2.7 on 2023-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_farequirementrepository_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farequirementrepository',
            name='requirement',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='inbrequirementrepository',
            name='requirement',
            field=models.CharField(default='', max_length=800),
        ),
    ]
